// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkzmbHf41Px3JQfld49gEfxFJJgFfKk4Y',
    appId: '1:839097271192:web:d53422cd062795efeaa1ed',
    messagingSenderId: '839097271192',
    projectId: 'flutter-notifications-53cb5',
    authDomain: 'flutter-notifications-53cb5.firebaseapp.com',
    storageBucket: 'flutter-notifications-53cb5.appspot.com',
    measurementId: 'G-T0YPZTCJFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDABkHcSnmmV7F52cZLdorwLg2are48y0',
    appId: '1:839097271192:android:bbdbbfec180226baeaa1ed',
    messagingSenderId: '839097271192',
    projectId: 'flutter-notifications-53cb5',
    storageBucket: 'flutter-notifications-53cb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw1jHmsymd8NundLV1-8EqB-wVm8o9l4E',
    appId: '1:839097271192:ios:d4bad186686d87f9eaa1ed',
    messagingSenderId: '839097271192',
    projectId: 'flutter-notifications-53cb5',
    storageBucket: 'flutter-notifications-53cb5.appspot.com',
    iosBundleId: 'com.example.flutterNotification',
  );
}
